# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anifan/Info_code_ws

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anifan/Info_code_ws

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anifan/Info_code_ws/CMakeFiles /home/anifan/Info_code_ws/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anifan/Info_code_ws/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uncoded

# Build rule for target.
uncoded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uncoded
.PHONY : uncoded

# fast build rule for target.
uncoded/fast:
	$(MAKE) -f CMakeFiles/uncoded.dir/build.make CMakeFiles/uncoded.dir/build
.PHONY : uncoded/fast

#=============================================================================
# Target rules for targets named BCJR

# Build rule for target.
BCJR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BCJR
.PHONY : BCJR

# fast build rule for target.
BCJR/fast:
	$(MAKE) -f CMakeFiles/BCJR.dir/build.make CMakeFiles/BCJR.dir/build
.PHONY : BCJR/fast

#=============================================================================
# Target rules for targets named Viterbi_hard

# Build rule for target.
Viterbi_hard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Viterbi_hard
.PHONY : Viterbi_hard

# fast build rule for target.
Viterbi_hard/fast:
	$(MAKE) -f CMakeFiles/Viterbi_hard.dir/build.make CMakeFiles/Viterbi_hard.dir/build
.PHONY : Viterbi_hard/fast

#=============================================================================
# Target rules for targets named Viterbi_soft

# Build rule for target.
Viterbi_soft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Viterbi_soft
.PHONY : Viterbi_soft

# fast build rule for target.
Viterbi_soft/fast:
	$(MAKE) -f CMakeFiles/Viterbi_soft.dir/build.make CMakeFiles/Viterbi_soft.dir/build
.PHONY : Viterbi_soft/fast

BCJR.o: BCJR.cpp.o

.PHONY : BCJR.o

# target to build an object file
BCJR.cpp.o:
	$(MAKE) -f CMakeFiles/BCJR.dir/build.make CMakeFiles/BCJR.dir/BCJR.cpp.o
.PHONY : BCJR.cpp.o

BCJR.i: BCJR.cpp.i

.PHONY : BCJR.i

# target to preprocess a source file
BCJR.cpp.i:
	$(MAKE) -f CMakeFiles/BCJR.dir/build.make CMakeFiles/BCJR.dir/BCJR.cpp.i
.PHONY : BCJR.cpp.i

BCJR.s: BCJR.cpp.s

.PHONY : BCJR.s

# target to generate assembly for a file
BCJR.cpp.s:
	$(MAKE) -f CMakeFiles/BCJR.dir/build.make CMakeFiles/BCJR.dir/BCJR.cpp.s
.PHONY : BCJR.cpp.s

Viterbi_hard.o: Viterbi_hard.cpp.o

.PHONY : Viterbi_hard.o

# target to build an object file
Viterbi_hard.cpp.o:
	$(MAKE) -f CMakeFiles/Viterbi_hard.dir/build.make CMakeFiles/Viterbi_hard.dir/Viterbi_hard.cpp.o
.PHONY : Viterbi_hard.cpp.o

Viterbi_hard.i: Viterbi_hard.cpp.i

.PHONY : Viterbi_hard.i

# target to preprocess a source file
Viterbi_hard.cpp.i:
	$(MAKE) -f CMakeFiles/Viterbi_hard.dir/build.make CMakeFiles/Viterbi_hard.dir/Viterbi_hard.cpp.i
.PHONY : Viterbi_hard.cpp.i

Viterbi_hard.s: Viterbi_hard.cpp.s

.PHONY : Viterbi_hard.s

# target to generate assembly for a file
Viterbi_hard.cpp.s:
	$(MAKE) -f CMakeFiles/Viterbi_hard.dir/build.make CMakeFiles/Viterbi_hard.dir/Viterbi_hard.cpp.s
.PHONY : Viterbi_hard.cpp.s

Viterbi_soft.o: Viterbi_soft.cpp.o

.PHONY : Viterbi_soft.o

# target to build an object file
Viterbi_soft.cpp.o:
	$(MAKE) -f CMakeFiles/Viterbi_soft.dir/build.make CMakeFiles/Viterbi_soft.dir/Viterbi_soft.cpp.o
.PHONY : Viterbi_soft.cpp.o

Viterbi_soft.i: Viterbi_soft.cpp.i

.PHONY : Viterbi_soft.i

# target to preprocess a source file
Viterbi_soft.cpp.i:
	$(MAKE) -f CMakeFiles/Viterbi_soft.dir/build.make CMakeFiles/Viterbi_soft.dir/Viterbi_soft.cpp.i
.PHONY : Viterbi_soft.cpp.i

Viterbi_soft.s: Viterbi_soft.cpp.s

.PHONY : Viterbi_soft.s

# target to generate assembly for a file
Viterbi_soft.cpp.s:
	$(MAKE) -f CMakeFiles/Viterbi_soft.dir/build.make CMakeFiles/Viterbi_soft.dir/Viterbi_soft.cpp.s
.PHONY : Viterbi_soft.cpp.s

uncoded.o: uncoded.cpp.o

.PHONY : uncoded.o

# target to build an object file
uncoded.cpp.o:
	$(MAKE) -f CMakeFiles/uncoded.dir/build.make CMakeFiles/uncoded.dir/uncoded.cpp.o
.PHONY : uncoded.cpp.o

uncoded.i: uncoded.cpp.i

.PHONY : uncoded.i

# target to preprocess a source file
uncoded.cpp.i:
	$(MAKE) -f CMakeFiles/uncoded.dir/build.make CMakeFiles/uncoded.dir/uncoded.cpp.i
.PHONY : uncoded.cpp.i

uncoded.s: uncoded.cpp.s

.PHONY : uncoded.s

# target to generate assembly for a file
uncoded.cpp.s:
	$(MAKE) -f CMakeFiles/uncoded.dir/build.make CMakeFiles/uncoded.dir/uncoded.cpp.s
.PHONY : uncoded.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... uncoded"
	@echo "... edit_cache"
	@echo "... BCJR"
	@echo "... Viterbi_hard"
	@echo "... Viterbi_soft"
	@echo "... BCJR.o"
	@echo "... BCJR.i"
	@echo "... BCJR.s"
	@echo "... Viterbi_hard.o"
	@echo "... Viterbi_hard.i"
	@echo "... Viterbi_hard.s"
	@echo "... Viterbi_soft.o"
	@echo "... Viterbi_soft.i"
	@echo "... Viterbi_soft.s"
	@echo "... uncoded.o"
	@echo "... uncoded.i"
	@echo "... uncoded.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

